{'Hora': '2023-11-23 10:29:13', 'Usuario': 'admin (Admin)', 'Error': "'tseg.models.Equipment object' has no attribute 'frecuencia_eq'"}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\users\routes.py", line 204, in search
    return render_template('search.html', title="Busqueda",
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\templates\search.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\templates\layout.html", line 65, in top-level template code
    {% block content %}
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\templates\search.html", line 55, in block 'content'
    <small class="article-title">Canal/Frec: <b>{{ equipment.frecuencia_eq.canal }} {{ equipment.frecuencia_eq.rango }}</b></small>
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'tseg.models.Equipment object' has no attribute 'frecuencia_eq'
{'Hora': '2023-11-23 10:35:32', 'Usuario': 'admin (Admin)', 'Error': "Encountered unknown tag 'endfor'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\users\routes.py", line 204, in search
    return render_template('search.html', title="Busqueda",
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\templates\search.html", line 57, in template
    {% endfor%}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
{'Hora': '2023-11-23 10:43:18', 'Usuario': 'admin (Admin)', 'Error': '<function like_op at 0x000002A14D3E7040>'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\users\routes.py", line 202, in search
    Modelo.marca.like('%'+searched+'%')))
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 683, in like
    return self.operate(like_op, other, escape=escape)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\attributes.py", line 444, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[return-value]  # noqa: E501
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 1994, in like_op
    return a.like(b, escape=escape)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 683, in like
    return self.operate(like_op, other, escape=escape)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 344, in operate
    raise NotImplementedError(str(op))
NotImplementedError: <function like_op at 0x000002A14D3E7040>
{'Hora': '2023-11-23 10:44:01', 'Usuario': 'admin (Admin)', 'Error': '<function like_op at 0x000002A14D3E7040>'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\users\routes.py", line 202, in search
    Modelo.marca.like('%'+searched+'%')))
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 683, in like
    return self.operate(like_op, other, escape=escape)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\attributes.py", line 444, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[return-value]  # noqa: E501
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 1994, in like_op
    return a.like(b, escape=escape)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 683, in like
    return self.operate(like_op, other, escape=escape)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\operators.py", line 344, in operate
    raise NotImplementedError(str(op))
NotImplementedError: <function like_op at 0x000002A14D3E7040>
{'Hora': '2023-11-23 10:45:27', 'Usuario': 'admin (Admin)', 'Error': 'Join target, typically a FROM expression, or ORM relationship attribute expected, got <sqlalchemy.sql.elements.BinaryExpression object at 0x0000029700DBB7C0>.'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\users\routes.py", line 201, in search
    modelos = Modelo.query.join(Marca.id == Modelo.marca_id).filter(or_(Modelo.nombre.like('%'+searched+'%'),
  File "<string>", line 2, in join
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\base.py", line 248, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in join
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\base.py", line 299, in generate
    fn(self, *args, **kw)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\query.py", line 2439, in join
    join_target = coercions.expect(
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\coercions.py", line 443, in expect
    return impl._implicit_coercions(
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\coercions.py", line 1269, in _implicit_coercions
    self._raise_for_expected(element, argname, resolved)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\coercions.py", line 536, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: Join target, typically a FROM expression, or ORM relationship attribute expected, got <sqlalchemy.sql.elements.BinaryExpression object at 0x0000029700DBB7C0>.
{'Hora': '2023-11-23 11:19:17', 'Usuario': 'admin (Admin)', 'Error': 'list.remove(x): x not in list'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\equipments\routes.py", line 129, in update_equipment
    equipment.frecuencias.remove(frecuencia)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\collections.py", line 1097, in remove
    fn(self, value)
ValueError: list.remove(x): x not in list
{'Hora': '2023-11-23 11:23:08', 'Usuario': 'admin (Admin)', 'Error': 'list.remove(x): x not in list'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\equipments\routes.py", line 133, in update_equipment
    equipment.frecuencias.remove(frecuencia)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\collections.py", line 1097, in remove
    fn(self, value)
ValueError: list.remove(x): x not in list
{'Hora': '2023-11-23 11:30:31', 'Usuario': 'admin (Admin)', 'Error': 'list.remove(x): x not in list'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\equipments\routes.py", line 133, in update_equipment
    equipment.frecuencias.remove(frecuencia)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\collections.py", line 1097, in remove
    fn(self, value)
ValueError: list.remove(x): x not in list
{'Hora': '2023-11-23 11:34:20', 'Usuario': 'admin (Admin)', 'Error': 'list.remove(x): x not in list'}
Traceback (most recent call last):
  File "C:\Documentos\Dropbox\Sistemas\Proyectos\TECSEG\tseg\equipments\routes.py", line 131, in update_equipment
    equipment.frecuencias.remove(frecuencia)
  File "C:\Users\NB5\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\collections.py", line 1097, in remove
    fn(self, value)
ValueError: list.remove(x): x not in list
{'Hora': '2023-11-25 13:32:46', 'Usuario': 'admin (Admin)', 'Error': "'OrdenTrabajoForm' object has no attribute 'comment'"}
Traceback (most recent call last):
  File "E:\Dropbox\Sistemas\Proyectos\TECSEG\tseg\ordenes_trabajo\routes.py", line 130, in update_orden_trabajo
    orden_trabajo.comment = form.comment.data
AttributeError: 'OrdenTrabajoForm' object has no attribute 'comment'
{'Hora': '2023-11-25 13:47:31', 'Usuario': 'admin (Admin)', 'Error': "'Equipment' object has no attribute 'frecuencia_olds'"}
Traceback (most recent call last):
  File "E:\Dropbox\Sistemas\Proyectos\TECSEG\tseg\equipments\routes.py", line 109, in update_equipment
    for frecuencia_old in equipment.frecuencia_olds:
AttributeError: 'Equipment' object has no attribute 'frecuencia_olds'
